version: 0.1.{build}
image: Visual Studio 2019 Preview
configuration: Release
before_build:
- pwsh: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- pwsh: 7z a dotnvim_x64.zip .\Dotnvim\bin\x64\Release\*.exe .\Dotnvim\bin\x64\Release\*.dll
artifacts:
- path: dotnvim_x64.zip